### ISSUE TITLE
OpenSSF scorecard report

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#52]
Work through the issues listed in [OpenSSF scorecard report](https://securityscorecards.dev/viewer/?uri=github.com/glamod/cdm_reader_mapper).

**Comment by ludwiglierhammer** [comment]
@jtsiddons: FYI, I added a new static code analysis workflow ([codeql.yml](https://github.com/glamod/cdm_reader_mapper/blob/main/.github/workflows/codeql.yml)). 

If you like, you are welcome to help me improve the scorecard report (see above link).

**Comment by ludwiglierhammer** [comment]
@jtsiddons: I already created a PR for security policy (#54)

**Comment by ludwiglierhammer** [comment]
@jtsiddons: do you have any ideas why codeql.yml workflow is running on PRs ?

E.g. #232 

```
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/*/*.yml
      - .pre-commit-config.yaml
      - CHANGELOG.rst
      - CI/*.txt
      - Makefile
      - docs/*/*.ipynb
      - docs/*/*.py
      - docs/*/*.rst
      - pyproject.toml
      - cdm_reader_mapper/__init__.py
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 23 * * 5'
```
